version: "3.7"
services:
  harness-ng-delegate:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2048M
    image: harness/delegate:22.11.77435
    environment:
      - ACCOUNT_ID=fh3GwEK0TV2Qjb-B4obkjw
      - DELEGATE_TOKEN=19e32d989a3b761763a7e3d1af76acd5
      - MANAGER_HOST_AND_PORT=https://app.harness.io/gratis
      - LOG_STREAMING_SERVICE_URL=https://app.harness.io/gratis/log-service/
      - DEPLOY_MODE=KUBERNETES
      - DELEGATE_NAME=traefik-test
      - NEXT_GEN=true
      - DELEGATE_TYPE=DOCKER
      - DELEGATE_TAGS=
      - INIT_SCRIPT=echo "Docker delegate init script executed."
# If proxy setting is required, Please refer to
# https://docs.harness.io/article/pfim3oig7o-configure-delegate-proxy-settings for Docker Proxy Settings
